# GitHub Actions Workflow: Test Functions
# Tests Crossplane composition functions

name: Test Composition Functions

on:
  pull_request:
    branches: [main]
    paths:
      - 'functions/**'
      - 'tests/**'
  push:
    branches: [main]
    paths:
      - 'functions/**'

jobs:
  test-functions:
    name: Test Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [patch-and-transform, go-templating, kcl]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
        if: matrix.function == 'python'
      
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
        if: matrix.function == 'go'
      
      - name: Install dependencies
        run: |
          if [ -f functions/${{ matrix.function }}/requirements.txt ]; then
            pip install -r functions/${{ matrix.function }}/requirements.txt
          fi
          if [ -f functions/${{ matrix.function }}/go.mod ]; then
            cd functions/${{ matrix.function }} && go mod download
          fi
      
      - name: Run function tests
        run: |
          cd functions/${{ matrix.function }}
          if [ -f test.sh ]; then
            bash test.sh
          elif [ -f Makefile ]; then
            make test
          else
            echo "No test script found"
          fi

  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'
      
      - name: Set up kind
        uses: helm/kind-action@v1
        with:
          install_kubectl: true
      
      - name: Create kind cluster
        run: |
          kind create cluster --name test-cluster --wait 5m
      
      - name: Install Crossplane
        run: |
          helm repo add crossplane-stable https://charts.crossplane.io/stable
          helm repo update
          helm install crossplane crossplane-stable/crossplane \
            --namespace crossplane-system \
            --create-namespace \
            --wait
      
      - name: Wait for Crossplane to be ready
        run: |
          kubectl wait --for=condition=Available deployment/crossplane \
            -n crossplane-system --timeout=5m
      
      - name: Run integration tests
        run: |
          ./tests/run-integration-tests.sh
      
      - name: Cleanup
        if: always()
        run: |
          kind delete cluster --name test-cluster

  lint-functions:
    name: Lint Functions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Lint Python functions
        run: |
          find functions -name "*.py" -exec pylint {} \;
        continue-on-error: true
      
      - name: Lint Go functions
        run: |
          find functions -name "*.go" -exec golangci-lint run {} \;
        continue-on-error: true

  build-functions:
    name: Build Functions
    runs-on: ubuntu-latest
    strategy:
      matrix:
        function: [patch-and-transform, go-templating, kcl]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build and push function image
        uses: docker/build-push-action@v5
        with:
          context: ./functions/${{ matrix.function }}
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/${{ matrix.function }}:${{ github.sha }}
            ghcr.io/${{ github.repository }}/${{ matrix.function }}:latest
