# Service Accounts for Crossplane
# These service accounts are used by Crossplane components

# ============================================
# Crossplane Core Service Account
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: crossplane
  namespace: crossplane-system
  labels:
    app: crossplane
    component: core

---
# ============================================
# AWS Provider Service Account
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-aws
  namespace: crossplane-system
  labels:
    app: crossplane
    component: provider
    provider: aws
  annotations:
    # For IRSA (IAM Roles for Service Accounts) on EKS
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789012:role/CrossplaneProviderRole

---
# ============================================
# Azure Provider Service Account
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-azure
  namespace: crossplane-system
  labels:
    app: crossplane
    component: provider
    provider: azure
  annotations:
    # For Workload Identity on AKS
    azure.workload.identity/client-id: "azure-client-id"

---
# ============================================
# GCP Provider Service Account
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: provider-gcp
  namespace: crossplane-system
  labels:
    app: crossplane
    component: provider
    provider: gcp
  annotations:
    # For Workload Identity on GKE
    iam.gke.io/gcp-service-account: crossplane-provider@project-id.iam.gserviceaccount.com

---
# ============================================
# Function Service Account (Example)
# ============================================

apiVersion: v1
kind: ServiceAccount
metadata:
  name: function-patch-and-transform
  namespace: crossplane-system
  labels:
    app: crossplane
    component: function
