# External Secrets Operator Examples
# Sync secrets from external systems to Kubernetes

# ============================================
# SecretStore for AWS Secrets Manager
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: aws-secrets-manager
  namespace: crossplane-system
spec:
  provider:
    aws:
      service: SecretsManager
      region: us-east-1
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator

---
# ============================================
# ExternalSecret for AWS Provider Credentials
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: aws-provider-creds
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: SecretStore
  target:
    name: aws-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials
      remoteRef:
        key: crossplane/aws/credentials
        property: credentials

---
# ============================================
# SecretStore for Azure Key Vault
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: azure-key-vault
  namespace: crossplane-system
spec:
  provider:
    azurekv:
      vaultUrl: https://myvault.vault.azure.net
      authType: WorkloadIdentity
      serviceAccountRef:
        name: external-secrets-operator

---
# ============================================
# ExternalSecret for Azure Provider Credentials
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: azure-provider-creds
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: azure-key-vault
    kind: SecretStore
  target:
    name: azure-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials
      remoteRef:
        key: crossplane-azure-credentials

---
# ============================================
# SecretStore for GCP Secret Manager
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: gcp-secret-manager
  namespace: crossplane-system
spec:
  provider:
    gcpsm:
      projectId: my-gcp-project
      auth:
        workloadIdentity:
          clusterLocation: us-central1
          clusterName: my-cluster
          serviceAccountRef:
            name: external-secrets-operator

---
# ============================================
# ExternalSecret for GCP Provider Credentials
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: gcp-provider-creds
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-manager
    kind: SecretStore
  target:
    name: gcp-creds
    creationPolicy: Owner
  data:
    - secretKey: credentials
      remoteRef:
        key: crossplane-gcp-credentials

---
# ============================================
# SecretStore for HashiCorp Vault
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: vault-backend
  namespace: crossplane-system
spec:
  provider:
    vault:
      server: https://vault.example.com:8200
      path: secret
      version: v2
      auth:
        kubernetes:
          mountPath: kubernetes
          role: external-secrets-operator
          serviceAccountRef:
            name: external-secrets-operator

---
# ============================================
# ExternalSecret for Vault
# ============================================

apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: vault-provider-creds
  namespace: crossplane-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: provider-creds
    creationPolicy: Owner
  data:
    - secretKey: aws-credentials
      remoteRef:
        key: crossplane/aws
        property: credentials
    - secretKey: azure-credentials
      remoteRef:
        key: crossplane/azure
        property: credentials
