# Sealed Secrets Examples
# Encrypt secrets for safe storage in Git

# ============================================
# Prerequisites
# ============================================
# 1. Install Sealed Secrets Controller:
#    kubectl apply -f https://github.com/bitnami-labs/sealed-secrets/releases/download/v0.24.0/controller.yaml
#
# 2. Get public key:
#    kubectl get secret -n kube-system -l sealedsecrets.bitnami.com/sealed-secrets-key -o yaml

---
# ============================================
# SealedSecret for AWS Credentials
# ============================================
# Note: This is an example. Actual sealed secrets are encrypted and cannot be created manually.
# Use kubeseal to create sealed secrets:
# kubectl create secret generic aws-creds --from-literal=credentials="..." --dry-run=client -o yaml | kubeseal -o yaml > sealed-secret.yaml

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: aws-creds
  namespace: crossplane-system
spec:
  encryptedData:
    # This is a placeholder - actual values are encrypted
    # Use kubeseal to generate the actual encrypted values
    credentials: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
  template:
    metadata:
      name: aws-creds
      namespace: crossplane-system
      labels:
        managed-by: sealed-secrets
    type: Opaque

---
# ============================================
# Example: Creating a Sealed Secret
# ============================================
#
# Step 1: Create a regular secret (do NOT commit this)
# kubectl create secret generic aws-creds \
#   --from-literal=credentials="[default]\naws_access_key_id=AKIA...\naws_secret_access_key=..." \
#   --dry-run=client -o yaml > secret.yaml
#
# Step 2: Seal the secret
# kubeseal -o yaml < secret.yaml > sealed-secret.yaml
#
# Step 3: Apply the sealed secret
# kubectl apply -f sealed-secret.yaml
#
# Step 4: Delete the unencrypted secret.yaml (NEVER commit it)
# rm secret.yaml

---
# ============================================
# SealedSecret for Azure Credentials
# ============================================

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: azure-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
  template:
    metadata:
      name: azure-creds
      namespace: crossplane-system
      labels:
        managed-by: sealed-secrets
    type: Opaque

---
# ============================================
# SealedSecret for GCP Credentials
# ============================================

apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: gcp-creds
  namespace: crossplane-system
spec:
  encryptedData:
    credentials: AgBy3i4OJSWK+PiTySYZZA9rO43cGDEQAx...
  template:
    metadata:
      name: gcp-creds
      namespace: crossplane-system
      labels:
        managed-by: sealed-secrets
    type: Opaque

---
# ============================================
# Best Practices for Sealed Secrets
# ============================================
#
# 1. Use kubeseal to create sealed secrets (never create manually)
# 2. Store sealed secrets in Git (they're encrypted)
# 3. Never commit unencrypted secrets
# 4. Rotate sealed secrets when credentials change
# 5. Use namespace-scoped sealed secrets when possible
# 6. Keep the sealing key secure (backup encryption keys)
