# Simple Composite Resource Definition (XRD) Example
# This defines a custom API for creating networks

apiVersion: apiextensions.crossplane.io/v1
kind: CompositeResourceDefinition
metadata:
  name: networks.network.example.org
spec:
  # API group for this resource
  group: network.example.org
  
  # Resource names
  names:
    kind: Network
    plural: networks
    singular: network
  
  # API versions
  versions:
    - name: v1alpha1
      served: true          # This version is served by the API
      referenceable: true   # Can be referenced by other resources
      
      # Schema definition - what users can provide
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
                - cidr
                - region
              properties:
                # CIDR block for the network
                cidr:
                  type: string
                  description: "CIDR block for the network (e.g., 10.0.0.0/16)"
                  pattern: '^([0-9]{1,3}\.){3}[0-9]{1,3}/[0-9]{1,2}$'
                
                # AWS region
                region:
                  type: string
                  description: "AWS region where the network will be created"
                  default: us-east-1
                
                # Optional: Environment tag
                environment:
                  type: string
                  description: "Environment name (development, staging, production)"
                  enum:
                    - development
                    - staging
                    - production
                  default: development
                
                # Optional: Enable DNS
                enableDns:
                  type: boolean
                  description: "Enable DNS resolution in the VPC"
                  default: true
---
# Example: How to use this XRD
# After applying this XRD, you can create Network resources:
#
# apiVersion: network.example.org/v1alpha1
# kind: Network
# metadata:
#   name: my-network
# spec:
#   cidr: 10.0.0.0/16
#   region: us-east-1
#   environment: production
#   enableDns: true
